name: cffconvert

on: push

jobs:
  convert:
    name: "convert"
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Convert CITATION.cff to Zenodo metadata format
        uses: citation-file-format/cffconvert-github-action@main
        with:
          args: "--infile ./CITATION.cff --format zenodo --outfile .zenodo.json"

      - name: Commit and create a Pull Request with the Zenodo file
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[:robot:] update .zenodo.json"
          committer: "cffconvert GitHub Action <cffconvert@users.noreply.github.com>"
          title: "[auto] Update .zenodo.json"
